/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ft4222
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FT4222_API_H
#define INCLUDED_FT4222_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ft4222_EXPORTS
#define FT4222_API __GR_ATTR_EXPORT
#else
#define FT4222_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FT4222_API_H */
